name: Continuous integration
run-name: ${{ github.actor }} is using out GitHub Actions 🚀
on: [push]
jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: make test